spring.application.name=video-service
server.port=8082

spring.datasource.url=${SUPABASE_DB_URL_VIDEO}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=video_schema

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:SSL}
spring.kafka.properties.ssl.keystore.type=PKCS12
spring.kafka.properties.ssl.keystore.location=${KAFKA_SSL_KEYSTORE_LOCATION:client.keystore.p12}
spring.kafka.properties.ssl.keystore.password=${KAFKA_SSL_KEYSTORE_PASSWORD:changeit}
spring.kafka.properties.ssl.key.password=${KAFKA_SSL_KEY_PASSWORD:${KAFKA_SSL_KEYSTORE_PASSWORD:changeit}}
spring.kafka.properties.ssl.truststore.type=JKS
spring.kafka.properties.ssl.truststore.location=${KAFKA_SSL_TRUSTSTORE_LOCATION:client.truststore.jks}
spring.kafka.properties.ssl.truststore.password=${KAFKA_SSL_TRUSTSTORE_PASSWORD:changeit}
spring.kafka.properties.ssl.endpoint.identification.algorithm=https
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

r2.account-id=${R2_ACCOUNT_ID}
r2.access-key-id=${R2_ACCESS_KEY_ID}
r2.secret-access-key=${R2_SECRET_ACCESS_KEY}
r2.bucket-name=${R2_BUCKET_NAME}

youtube.api-key=${YOUTUBE_API_KEY:}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
