export const categories = [
  "For you",
  "Fashion",
  "Music",
  "Sport",
  "Food",
  "Travel",
  "Gaming",
  "Backend",
  "Frontend",
  "AI",
  "Data",
  "DevOps",
  "Design",
  "Education",
];

export const videos = [
  {
    title: "Paris streetwear lookbook",
    creator: "lina_style",
    channel: "Lina Style Studio",
    views: "18.4k",
    uploadedAt: "8 hours ago",
    duration: "09:31",
    category: "Fashion",
    score: "98%",
    poster: "fashion",
    description:
      "A clean streetwear lookbook with color matching, silhouettes, and practical outfit ideas.",
  },
  {
    title: "Summer outfits for every day",
    creator: "maya_fit",
    channel: "Maya Fashion",
    views: "22k",
    uploadedAt: "2 days ago",
    duration: "11:44",
    category: "Fashion",
    score: "95%",
    poster: "fashion2",
    description:
      "Simple summer outfit combinations with accessories, shoes, and styling details.",
  },
  {
    title: "Studio playlist: chill pop session",
    creator: "noah_sound",
    channel: "Noah Sound Room",
    views: "31k",
    uploadedAt: "1 day ago",
    duration: "28:05",
    category: "Music",
    score: "93%",
    poster: "music",
    description:
      "A relaxed pop session with warm vocals, clean drums, and late-night studio energy.",
  },
  {
    title: "Full body football training",
    creator: "coach_adam",
    channel: "Adam Performance",
    views: "14.7k",
    uploadedAt: "4 days ago",
    duration: "17:18",
    category: "Sport",
    score: "90%",
    poster: "sport",
    description:
      "Speed, balance, and strength exercises for football players training at home or on pitch.",
  },
  {
    title: "Moroccan dinner in 20 minutes",
    creator: "sara_cooks",
    channel: "Sara Cooks",
    views: "19.1k",
    uploadedAt: "3 days ago",
    duration: "13:02",
    category: "Food",
    score: "92%",
    poster: "food",
    description:
      "A quick, colorful dinner inspired by Moroccan flavors with simple pantry ingredients.",
  },
  {
    title: "Marrakech weekend travel guide",
    creator: "amine_trip",
    channel: "Amine Travel",
    views: "27.5k",
    uploadedAt: "5 days ago",
    duration: "19:27",
    category: "Travel",
    score: "91%",
    poster: "travel",
    description:
      "A weekend guide with hidden spots, food stops, rooftop views, and practical itinerary tips.",
  },
  {
    title: "Best indie games to play tonight",
    creator: "ray_game",
    channel: "Ray Gaming",
    views: "44k",
    uploadedAt: "12 hours ago",
    duration: "15:49",
    category: "Gaming",
    score: "96%",
    poster: "gaming",
    description:
      "Fast recommendations for stylish indie games with strong art direction and smooth gameplay.",
  },
  {
    title: "Spring Boot REST API guide",
    creator: "alice_dev",
    channel: "Alice Dev Channel",
    views: "2.1k",
    uploadedAt: "2 weeks ago",
    duration: "18:42",
    category: "Backend",
    score: "94%",
    poster: "api",
    description:
      "Build a production-ready API with validation, security, and clean service boundaries.",
  },
  {
    title: "Kafka streams deep dive",
    creator: "alice_dev",
    channel: "Alice Dev Channel",
    views: "3.8k",
    uploadedAt: "3 days ago",
    duration: "24:10",
    category: "Data",
    score: "91%",
    poster: "streams",
    description:
      "Understand stream processing patterns for recommendation events and analytics.",
  },
  {
    title: "Docker deployment workflow",
    creator: "carol_s",
    channel: "Carol's Tech",
    views: "5.2k",
    uploadedAt: "5 days ago",
    duration: "12:08",
    category: "DevOps",
    score: "88%",
    poster: "docker",
    description:
      "Package services cleanly and move from local Compose to production environments.",
  },
  {
    title: "Recommendation models explained",
    creator: "eve_ai",
    channel: "Eve's AI",
    views: "12k",
    uploadedAt: "1 day ago",
    duration: "21:36",
    category: "AI",
    score: "97%",
    poster: "ai",
    description:
      "A practical look at collaborative filtering, ranking, and freshness signals.",
  },
  {
    title: "SQL joins without confusion",
    creator: "henry_db",
    channel: "Henry's Database",
    views: "4.1k",
    uploadedAt: "1 week ago",
    duration: "15:03",
    category: "Data",
    score: "86%",
    poster: "database",
    description:
      "Write readable joins and avoid common query mistakes in service databases.",
  },
  {
    title: "React state patterns for apps",
    creator: "grace_dev",
    channel: "Grace Dev",
    views: "5.3k",
    uploadedAt: "6 days ago",
    duration: "16:55",
    category: "Frontend",
    score: "89%",
    poster: "react",
    description:
      "Model UI state clearly for auth flows, dashboards, and responsive views.",
  },
];

export const comments = [
  {
    author: "bob123",
    avatar: "B",
    text: "Great tutorial. The service structure finally clicked for me.",
    timestamp: "1 day ago",
    likes: 24,
  },
  {
    author: "carol_s",
    avatar: "C",
    text: "The validation and error response examples are exactly what I needed.",
    timestamp: "3 hours ago",
    likes: 8,
  },
  {
    author: "dave_code",
    avatar: "D",
    text: "A follow-up on Spring Security would be useful.",
    timestamp: "5 hours ago",
    likes: 15,
  },
];

export const users = [
  { username: "alice_dev", email: "alice@ex.com", role: "USER", status: "Active", joined: "Nov 1" },
  { username: "bob123", email: "bob@ex.com", role: "USER", status: "Banned", joined: "Oct 28" },
  { username: "superadmin", email: "admin@ex.com", role: "ADMIN", status: "Active", joined: "Oct 1" },
  { username: "carol_s", email: "carol@ex.com", role: "USER", status: "Active", joined: "Nov 3" },
];
